version: '3.8'

services:
  ignews-frontend:
    container_name: ignews-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    tty: true